import React, { useState, useEffect } from 'react';
import { 
  Bell, 
  CheckCircle2, 
  AlertTriangle, 
  Radio, 
  GitMerge, 
  Trash2, 
  PlusCircle,
  Clock,
  Sparkles
} from 'lucide-react';
import { mockStore } from '../supabase/supabaseClient';
import { usePageTransition } from '../hooks/usePageTransition';

export const NotificationsPage = ({ onNavigate }) => {
  const pageRef = usePageTransition('notifications');
  const [notifications, setNotifications] = useState([]);

  useEffect(() => {
    setNotifications(mockStore.getNotifications());
    const unsub = mockStore.subscribe((e) => {
      setNotifications(mockStore.getNotifications());
    });
    return () => unsub();
  }, []);

  const handleSimulateAlert = () => {
    mockStore.addNotification({
      title: 'NEW CIVIC REPORT: Pothole Detected',
      message: 'Ward 14 • 18m from CIV-001 • Duplicate confidence: 89% • Priority: MEDIUM → HIGH.',
      type: 'warning'
    });
  };

  const handleClear = () => {
    localStorage.setItem('civicflow_notifications', JSON.stringify([]));
    setNotifications([]);
  };

  return (
    <div ref={pageRef} className="max-w-4xl mx-auto pt-28 pb-16 px-4 space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <span className="text-xs font-mono font-bold text-cyan-400 uppercase tracking-widest">
            Supabase Realtime Stream
          </span>
          <h2 className="text-3xl font-display font-black text-white mt-1">
            Realtime Operations Feed
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Autonomous alerts generated by spatial duplicate matching, sensor thresholds, and superintendent dispatches.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleSimulateAlert}
            className="px-4 py-2 rounded-xl bg-cyan-500/20 hover:bg-cyan-500/30 text-cyan-300 border border-cyan-500/40 text-xs font-semibold flex items-center gap-1.5"
          >
            <PlusCircle className="w-3.5 h-3.5" />
            <span>Simulate Incoming Alert</span>
          </button>
          <button
            onClick={handleClear}
            className="p-2 rounded-xl bg-slate-900 border border-slate-700 text-slate-400 hover:text-red-400"
            title="Clear all alerts"
          >
            <Trash2 className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="glass-panel bg-slate-950/85 p-6 rounded-3xl border border-cyan-500/30 shadow-2xl backdrop-blur-xl">
        <div className="space-y-3">
          {notifications.length > 0 ? (
            notifications.map((n) => (
              <div
                key={n.id}
                className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 hover:border-cyan-500/40 transition-colors flex items-start gap-3.5"
              >
                <div className={`p-2.5 rounded-xl flex-shrink-0 ${
                  n.type === 'success' ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/40' :
                  n.type === 'warning' ? 'bg-amber-500/20 text-amber-400 border border-amber-500/40' :
                  'bg-cyan-500/20 text-cyan-400 border border-cyan-500/40'
                }`}>
                  {n.type === 'success' ? <CheckCircle2 className="w-4 h-4" /> :
                   n.type === 'warning' ? <AlertTriangle className="w-4 h-4" /> :
                   <Radio className="w-4 h-4" />}
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between">
                    <h4 className="text-xs font-bold text-white">{n.title}</h4>
                    <span className="text-[10px] font-mono text-slate-500">{n.time}</span>
                  </div>
                  <p className="text-xs text-slate-300 mt-1 leading-relaxed">{n.message}</p>
                </div>
              </div>
            ))
          ) : (
            <div className="text-center py-16 text-slate-500 text-xs">
              No alerts in stream. Press "Simulate Incoming Alert" to test real-time notification push.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default NotificationsPage;
